import React from 'react';
import { X, Volume2, Mic, Radio, Zap, Globe, Sliders } from 'lucide-react';
import { SpeechSettings, NEURAL_VOICES } from '../utils/speechEngine';

interface SettingsModalProps {
  isOpen: boolean;
  onClose: () => void;
  settings: SpeechSettings;
  onUpdateSettings: (newSettings: Partial<SpeechSettings>) => void;
  browserVoices: SpeechSynthesisVoice[];
}

export const SettingsModal: React.FC<SettingsModalProps> = ({
  isOpen,
  onClose,
  settings,
  onUpdateSettings,
  browserVoices,
}) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-200">
      <div className="relative w-full max-w-lg rounded-2xl border border-cyan-500/40 bg-slate-950/95 p-6 shadow-[0_0_50px_rgba(6,182,212,0.25)] text-slate-100 font-sans">
        {/* Hologram Header */}
        <div className="flex items-center justify-between border-b border-cyan-500/30 pb-4">
          <div className="flex items-center gap-2">
            <Sliders className="w-5 h-5 text-cyan-400" />
            <h2 className="font-cyber text-lg tracking-wider text-cyan-300 font-bold uppercase">
              MysterioTrap Neural Voice Settings
            </h2>
          </div>
          <button
            onClick={onClose}
            className="rounded-lg p-1.5 text-slate-400 hover:text-cyan-300 hover:bg-cyan-950/40 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="space-y-6 py-4 max-h-[75vh] overflow-y-auto pr-1">
          {/* Voice Engine Mode */}
          <div>
            <label className="block text-xs font-cyber tracking-wider text-cyan-400 uppercase mb-2">
              Voice Synthesis Engine
            </label>
            <div className="grid grid-cols-2 gap-3">
              <button
                type="button"
                onClick={() => onUpdateSettings({ engine: 'native' })}
                className={`flex flex-col p-3 rounded-xl border text-left transition-all ${
                  settings.engine === 'native'
                    ? 'border-cyan-400 bg-cyan-950/50 shadow-[0_0_15px_rgba(6,182,212,0.3)]'
                    : 'border-slate-800 bg-slate-900/50 hover:border-slate-700'
                }`}
              >
                <div className="flex items-center gap-2 text-cyan-300 font-semibold text-sm">
                  <Zap className="w-4 h-4 text-emerald-400" />
                  Instant Native Voice
                </div>
                <p className="text-[11px] text-slate-400 mt-1">
                  Zero latency (&lt;100ms), instant response using device hardware.
                </p>
                <span className="mt-2 text-[10px] uppercase font-mono px-2 py-0.5 rounded bg-emerald-500/20 text-emerald-300 self-start">
                  Recommended for Speed
                </span>
              </button>

              <button
                type="button"
                onClick={() => onUpdateSettings({ engine: 'neural' })}
                className={`flex flex-col p-3 rounded-xl border text-left transition-all ${
                  settings.engine === 'neural'
                    ? 'border-cyan-400 bg-cyan-950/50 shadow-[0_0_15px_rgba(6,182,212,0.3)]'
                    : 'border-slate-800 bg-slate-900/50 hover:border-slate-700'
                }`}
              >
                <div className="flex items-center gap-2 text-cyan-300 font-semibold text-sm">
                  <Radio className="w-4 h-4 text-cyan-400" />
                  Gemini Studio Neural
                </div>
                <p className="text-[11px] text-slate-400 mt-1">
                  Ultra-lifelike neural voice generated by gemini-3.8-flash-lite-tts.
                </p>
                <span className="mt-2 text-[10px] uppercase font-mono px-2 py-0.5 rounded bg-cyan-500/20 text-cyan-300 self-start">
                  Cinematic Quality
                </span>
              </button>
            </div>
          </div>

          {/* Voice Selector */}
          <div>
            <label className="block text-xs font-cyber tracking-wider text-cyan-400 uppercase mb-2">
              Persona & Voice Tone
            </label>
            {settings.engine === 'neural' ? (
              <select
                value={settings.voiceName || 'Fenrir'}
                onChange={(e) => onUpdateSettings({ voiceName: e.target.value })}
                className="w-full bg-slate-900 border border-cyan-500/30 rounded-lg px-3 py-2 text-sm text-cyan-200 focus:outline-none focus:border-cyan-400"
              >
                {NEURAL_VOICES.map((v) => (
                  <option key={v.id} value={v.id}>
                    {v.name}
                  </option>
                ))}
              </select>
            ) : (
              <select
                value={settings.voiceName}
                onChange={(e) => onUpdateSettings({ voiceName: e.target.value })}
                className="w-full bg-slate-900 border border-cyan-500/30 rounded-lg px-3 py-2 text-sm text-cyan-200 focus:outline-none focus:border-cyan-400"
              >
                <option value="">Default Jarvis Matrix Voice (Auto-optimizing)</option>
                {browserVoices.map((voice, idx) => (
                  <option key={`${voice.name}-${idx}`} value={voice.name}>
                    {voice.name} ({voice.lang})
                  </option>
                ))}
              </select>
            )}
          </div>

          {/* Language Preference */}
          <div>
            <label className="block text-xs font-cyber tracking-wider text-cyan-400 uppercase mb-2 flex items-center gap-2">
              <Globe className="w-4 h-4 text-cyan-400" />
              Language / Bhasha Mode
            </label>
            <div className="grid grid-cols-3 gap-2">
              {[
                { id: 'auto', label: 'Auto (Hinglish/Any)' },
                { id: 'en', label: 'English (Jarvis)' },
                { id: 'hi', label: 'हिन्दी (Hindi)' },
              ].map((lang) => (
                <button
                  key={lang.id}
                  type="button"
                  onClick={() => onUpdateSettings({ language: lang.id as any })}
                  className={`py-2 px-3 rounded-lg text-xs font-semibold border transition-all text-center ${
                    settings.language === lang.id
                      ? 'border-cyan-400 bg-cyan-500/20 text-cyan-200 shadow-[0_0_10px_rgba(6,182,212,0.3)]'
                      : 'border-slate-800 bg-slate-900/60 text-slate-400 hover:text-slate-200'
                  }`}
                >
                  {lang.label}
                </button>
              ))}
            </div>
          </div>

          {/* Speed & Pitch Controls (Native Engine) */}
          {settings.engine === 'native' && (
            <div className="grid grid-cols-2 gap-4 border-t border-cyan-900/40 pt-4">
              <div>
                <div className="flex justify-between text-xs text-slate-300 mb-1">
                  <span>Speech Speed</span>
                  <span className="font-mono text-cyan-400 font-semibold">
                    {settings.rate}x
                  </span>
                </div>
                <input
                  type="range"
                  min="0.8"
                  max="1.5"
                  step="0.05"
                  value={settings.rate}
                  onChange={(e) => onUpdateSettings({ rate: parseFloat(e.target.value) })}
                  className="w-full accent-cyan-400 h-1.5 bg-slate-800 rounded-lg cursor-pointer"
                />
              </div>

              <div>
                <div className="flex justify-between text-xs text-slate-300 mb-1">
                  <span>Voice Pitch</span>
                  <span className="font-mono text-cyan-400 font-semibold">
                    {settings.pitch}x
                  </span>
                </div>
                <input
                  type="range"
                  min="0.7"
                  max="1.3"
                  step="0.05"
                  value={settings.pitch}
                  onChange={(e) => onUpdateSettings({ pitch: parseFloat(e.target.value) })}
                  className="w-full accent-cyan-400 h-1.5 bg-slate-800 rounded-lg cursor-pointer"
                />
              </div>
            </div>
          )}

          {/* Hands-Free Continuous Mode Toggle */}
          <div className="border-t border-cyan-900/40 pt-4">
            <div className="flex items-center justify-between">
              <div>
                <div className="flex items-center gap-2">
                  <Mic className="w-4 h-4 text-emerald-400" />
                  <span className="text-sm font-semibold text-slate-200">
                    Hands-Free Continuous Listening
                  </span>
                </div>
                <p className="text-xs text-slate-400 mt-0.5">
                  MysterioTrap will automatically listen for your next question after finishing speaking.
                </p>
              </div>

              <button
                type="button"
                onClick={() => onUpdateSettings({ continuousMode: !settings.continuousMode })}
                className={`relative inline-flex h-6 w-11 shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none ${
                  settings.continuousMode ? 'bg-emerald-500 shadow-[0_0_12px_#10b981]' : 'bg-slate-800'
                }`}
              >
                <span
                  className={`pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out ${
                    settings.continuousMode ? 'translate-x-5' : 'translate-x-0'
                  }`}
                />
              </button>
            </div>
          </div>
        </div>

        {/* Action Button */}
        <div className="mt-4 pt-3 border-t border-cyan-500/30 flex justify-end">
          <button
            onClick={onClose}
            className="px-5 py-2 rounded-xl bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-cyber font-bold text-xs uppercase tracking-wider shadow-[0_0_15px_rgba(6,182,212,0.4)] transition-all"
          >
            Save & Sync System
          </button>
        </div>
      </div>
    </div>
  );
};
